version: '3.8'

services:
    app:
        build: .
        container_name: ordem-servico-app
        ports:
            - "8000:80"
        volumes:
            - ./database:/var/www/html/database
            - ./storage:/var/www/html/storage
        environment:
            - APP_ENV=production
            - APP_DEBUG=true
            - DB_CONNECTION=sqlite
            - DB_DATABASE=/var/www/html/database/database.sqlite
        restart: unless-stopped
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost/"]
            interval: 30s
            timeout: 10s
            retries: 3
            start_period: 40s
volumes:
    database_data:
    storage_data:

